# Project info
site_name: IBM watsonx Code Assistant for Practitioners Level 4
site_description: IBM watsonx Code Assistant for Practitioners Level 4
site_author: Christopher Bienko (cdbienko@us.ibm.com)
copyright: Copyright &copy; 2025 IBM

# Repository
repo_name: IBM/wca-l4
#repo_url: https://github.com/IBM/wca-l4
#edit_uri: edit/master/docs
docs_dir: docs

nav:
  - Introduction: 'index.md'
  - On-Premises Installation and Deployment:
    - 1. Objectives and requirements: 'on-premises/1.md'
    - 2. Reserve an environment: 'on-premises/2.md'
    - 3. Bastion host setup: 'on-premises/3.md'
    - 4. Cluster preparation: 'on-premises/4.md'
    - 5. Install prerequisite software: 'on-premises/5.md'
    - 6. Install IBM Software Hub: 'on-premises/6.md'
    - 7. Install watsonx Code Assistant: 'on-premises/7.md'
  - IBM Cloud (SaaS) Configuration:
    - 1. Objectives and requirements: 'saas/1.md'
    - 2. Reserve an environment: 'saas/2.md'
    - 3. Install WCA extension for Visual Studio Code: 'saas/3.md'
    - 4. Install WCA plug-in for Eclipse IDE: 'saas/4.md'
  - Application Modernization - WebSphere to Liberty:
    - 1. Objectives and requirements: 'appmod1/1.md'
    - 2. Basic migration capabilities: 'appmod1/2.md'
    - 3. Configuration management: 'appmod1/3.md'
    - 4. APIs and libraries: 'appmod1/4.md'
    - 5. EJB modernization: 'appmod1/5.md'
    - 6. JSP modernization: 'appmod1/6.md'
    - 7. Security modernization: 'appmod1/7.md'
    - 8. Data source pooling: 'appmod1/8.md'
    - 9. JMS messaging integration: 'appmod1/9.md'
    - 10. State handling: 'appmod1/10.md'
    - 11. Load balancing: 'appmod1/11.md'
    - 12. Performance optimization: 'appmod1/12.md'
    - 13. Logging and monitoring: 'appmod1/13.md'
  - Tuning and Customization:
    - 1. Getting code suggestions: 'tuning/1.md'
    - 2. Explaining code: 'tuning/2.md'
    - 3. Documenting code: 'tuning/3.md'
    - 4. Unit test generation: 'tuning/4.md'
    - 5. Upgrading Java versions: 'tuning/5.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
  palette:
      scheme: default

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
  - macros
  - search
  - glightbox
  - print-site:
      add_to_navigation: false
      print_page_title: 'IBM watsonx Code Assistant for Practitioners Level 4 Lab Guide'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: false
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: false
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true

markdown_extensions:
  - markdown_fenced_code_tabs
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables